### ISSUE TITLE
Run typogrify again

### ISSUE THREAD

**Issue by acabal** [bendix3/max-beerbohm_the-works-of-max-beerbohm#3]
Another run will correct a few oversights introduced after you ran it earlier

**Comment by acabal** [comment]
Also, run semanticate one more time as well, as that inserts additional semantics missed during an earlier run.

**Comment by bendix3** [comment]
I ran both and as you said, they found a few oversights. I didn't let typogrify change my `&amp;,` in "Therefore desist your irksome attention &amp;, if […]" to a unicode ampersand, though. I suppose this is a bug?
